import { PromotionalRule } from './types/discount';

export const MOCK_RULES: PromotionalRule[] = [
  {
    id: '1',
    name: 'EQP Summer Special',
    description: 'EQP - 3% with Half MOQ',
    logic: 'EQP',
    isAutomatic: false,
    baseType: 'EQP',
    selectedLogics: ['EQP'],
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 0, discountAmount: 0 }],
    flatDiscountApplyOnBasket: false,
    eqpModifier: '3%',
    moqOption: 'HALF',
    setupOption: 'NONE',
    scope: 'SITEWIDE',
    productIds: [],
    status: 'ACTIVE',
    startDate: '2025-11-01',
    endDate: '2025-12-31',
    promoCode: 'SUMMER3',
    applyOnFirstTimeBuyer: false,
    promoCodeUseOneTime: true,
    applyOnItemPlusCharges: false
  },
  {
    id: '2',
    name: 'VIP Flat Discount',
    description: '$50 off for VIP customers',
    logic: 'FLAT_AMOUNT',
    isAutomatic: true,
    baseType: 'FLAT_DISCOUNT',
    selectedLogics: ['FLAT_DISCOUNT'],
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 100, discountAmount: 50 }],
    flatDiscountApplyOnBasket: true,
    eqpModifier: 'NONE',
    moqOption: 'NONE',
    setupOption: 'NONE',
    scope: 'PRODUCT',
    productIds: ['PROD-001'],
    status: 'ACTIVE',
    startDate: '2023-04-03',
    endDate: '2026-12-31',
    applyOnFirstTimeBuyer: true,
    promoCodeUseOneTime: false,
    applyOnItemPlusCharges: true
  },
  {
    id: '3',
    name: 'Bulk Order Discount',
    description: '$100 off for orders over $1000',
    logic: 'FLAT_AMOUNT',
    isAutomatic: true,
    baseType: 'FLAT_DISCOUNT',
    selectedLogics: ['FLAT_DISCOUNT'],
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 1000, discountAmount: 100 }],
    flatDiscountApplyOnBasket: true,
    eqpModifier: 'NONE',
    moqOption: 'NONE',
    setupOption: 'NONE',
    scope: 'SITEWIDE',
    productIds: [],
    status: 'ACTIVE',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    applyOnFirstTimeBuyer: false,
    promoCodeUseOneTime: false,
    applyOnItemPlusCharges: false
  },
  {
    id: '4',
    name: 'Free Shipping Over $200',
    description: 'Free standard shipping for large orders',
    logic: 'SHIPPING_FLAT',
    isAutomatic: true,
    baseType: 'SHIPPING_DISCOUNT',
    selectedLogics: ['SHIPPING_DISCOUNT'],
    shippingDiscountType: 'FREE',
    shippingDiscountValue: 0,
    shippingMethods: ['UPS-Ground#1ab20e81-97c8-464e-81be-15170c9e5ae5'],
    shippingMinOrderAmount: 200,
    eqpModifier: 'NONE',
    moqOption: 'NONE',
    setupOption: 'NONE',
    scope: 'SITEWIDE',
    productIds: [],
    status: 'ACTIVE',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    applyOnFirstTimeBuyer: false,
    promoCodeUseOneTime: false,
    applyOnItemPlusCharges: false
  }
];
