import { DiscountRule } from './types/discount';

export const MOCK_RULES: DiscountRule[] = [
  {
    id: '1',
    name: 'EQP Summer Special',
    description: 'EQP - 3% with Half MOQ',
    logic: 'EQP',
    isAutomatic: false,
    baseType: 'EQP',
    combinableWith: ['FLAT_DISCOUNT', 'SHIPPING_DISCOUNT'],
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 0, discountAmount: 0 }],
    applyOnBasketPrice: false,
    eqpModifier: '3%',
    moqOption: 'HALF',
    setupOption: 'NONE',
    value: 0,
    scope: 'SITEWIDE',
    targetIds: [],
    status: 'ACTIVE',
    startDate: '2025-11-01',
    endDate: '2025-12-31',
    promoCode: 'SUMMER3',
    applyOnFirstTimeBuyer: false,
    promoCodeUseOneTime: true,
    applyOnItemPrice: true,
    applyOnItemPlusCharges: false
  },
  {
    id: '2',
    name: 'VIP Flat Discount',
    description: '$50 off for VIP customers',
    logic: 'FLAT_AMOUNT',
    isAutomatic: true,
    baseType: 'FLAT_DISCOUNT',
    combinableWith: ['SHIPPING_DISCOUNT'],
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 100, discountAmount: 50 }],
    applyOnBasketPrice: true,
    eqpModifier: 'NONE',
    moqOption: 'NONE',
    setupOption: 'NONE',
    value: 50,
    scope: 'PRODUCT',
    targetIds: ['PROD-001'],
    status: 'ACTIVE',
    startDate: '2023-04-03',
    endDate: '2026-12-31',
    applyOnFirstTimeBuyer: true,
    promoCodeUseOneTime: false,
    applyOnItemPrice: false,
    applyOnItemPlusCharges: true
  },
  {
    id: '3',
    name: 'Free Shipping Over $200',
    description: 'Free standard shipping for large orders',
    logic: 'SHIPPING_FLAT',
    value: 0,
    isAutomatic: true,
    baseType: 'SHIPPING_DISCOUNT',
    combinableWith: ['EQP', 'FLAT_DISCOUNT'],
    shippingDiscountType: 'FREE',
    shippingMethods: ['UPS-Ground#1ab20e81-97c8-464e-81be-15170c9e5ae5'],
    minOrderAmount: 200,
    flatDiscountType: 'AMOUNT',
    tieredFlatDiscounts: [{ minOrderAmount: 0, discountAmount: 0 }],
    applyOnBasketPrice: false,
    eqpModifier: 'NONE',
    moqOption: 'NONE',
    setupOption: 'NONE',
    scope: 'SITEWIDE',
    targetIds: [],
    status: 'ACTIVE',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    applyOnFirstTimeBuyer: false,
    promoCodeUseOneTime: false,
    applyOnItemPrice: false,
    applyOnItemPlusCharges: false
  }
];
